const READY = 'READY';
const BUILDING = 'BUILDING';
const INDEXING = 'INDEXING';
const UNKNOWN = 'UNKNOWN';
const NO_FILE = 'NO_FILE';

module.exports = {
	READY: READY,
	BUILDING: BUILDING,
	INDEXING: INDEXING,
	UNKNOWN: UNKNOWN,
	NO_FILE: NO_FILE
};